import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { useNavigate } from 'react-router-dom'
import { useAuth } from '../hooks/useAuth'
import { useToast } from '../hooks/useToast'
import { api } from '../services/api'
import type { Comment, Post, Reaction, ReactionType, User } from '../types'
import { SeriesProgress } from '../pages/SeriesPages'
import { ChevronDown, Gem, Lightbulb, MessageCircle, Pin, Send, Wrench, type LucideIcon } from 'lucide-react'

const reactionOptions: {type:ReactionType;label:string;icon:LucideIcon}[]=[{type:'insightful',label:'Insightful',icon:Lightbulb},{type:'beautiful',label:'Beautiful',icon:Gem},{type:'useful',label:'Useful',icon:Wrench}]
function reactionTotal(reactions:Reaction[]|undefined){return reactions?.length??0}
function optimisticReaction(reactions:Reaction[]|undefined,userId:string,type:ReactionType){const values=reactions??[];const current=values.find(item=>item.user_id===userId);const rest=values.filter(item=>item.user_id!==userId);return current?.type===type?rest:[...rest,{user_id:userId,type}]}

function ReactionBar({reactions,onReact}: {reactions?:Reaction[];onReact:(type:ReactionType)=>void}) {
  const {user}=useAuth()
  return <div className="reaction-bar" aria-label="Reactions">{reactionOptions.map(option=>{const count=(reactions??[]).filter(item=>item.type===option.type).length;const active=(reactions??[]).some(item=>item.user_id===user?.id&&item.type===option.type);const Icon=option.icon;return <button type="button" className={active?'active':''} aria-pressed={active} onClick={()=>onReact(option.type)} key={option.type}><span><Icon aria-hidden="true"/></span>{option.label}{count>0&&<b>{count}</b>}</button>})}</div>
}

function CommentComposer({post,parent,candidates,onCreated,onCancel}: {post:Post;parent?:Comment;candidates:User[];onCreated:(comment:Comment)=>void;onCancel?:()=>void}) {
  const {user}=useAuth();const toast=useToast();const navigate=useNavigate();const [content,setContent]=useState(parent?.user?.name?`@${parent.user.name} `:'');const [mentions,setMentions]=useState<string[]>(parent?.user?.id?[parent.user.id]:[]);const [suggestions,setSuggestions]=useState<User[]>([]);const [busy,setBusy]=useState(false)
  function change(value:string){setContent(value);const match=value.match(/@([^@\n]{0,40})$/u);if(!match){setSuggestions([]);return}const query=match[1].toLocaleLowerCase().trim();setSuggestions(candidates.filter(candidate=>candidate.id!==user?.id&&(!query||candidate.name.toLocaleLowerCase().includes(query))).slice(0,5))}
  function mention(candidate:User){setContent(value=>value.replace(/@([^@\n]{0,40})$/u,`@${candidate.name} `));setMentions(value=>[...new Set([...value,candidate.id])]);setSuggestions([])}
  async function submit(event:FormEvent){event.preventDefault();if(!user){toast('Please sign in before joining the conversation.','error');navigate('/login');return}if(!content.trim()||busy)return;setBusy(true);try{const created=await api.comment(post.slug,content,parent?.id??'',mentions);onCreated(created);setContent('');setMentions([]);setSuggestions([]);if(created.status==='pending')toast('Your response was flagged for moderation.','info');else toast(parent?'Reply published.':'Comment published.')}catch(error){toast(error instanceof Error?error.message:'Unable to publish your response.','error')}finally{setBusy(false)}}
  return <form className={`comment-composer${parent?' reply-composer':''}`} onSubmit={submit}><div className="comment-input-wrap"><textarea value={content} onChange={event=>change(event.target.value)} placeholder={parent?`Reply to ${parent.user?.name??'this comment'}…`:'Share a thoughtful response…'} aria-label={parent?'Write a reply':'Write a response'} required maxLength={4000}/>{suggestions.length>0&&<div className="mention-menu" role="listbox" aria-label="Mention a person">{suggestions.map(candidate=><button type="button" role="option" key={candidate.id} onMouseDown={event=>event.preventDefault()} onClick={()=>mention(candidate)}><span className="avatar">{candidate.avatar?<img src={candidate.avatar} alt=""/>:candidate.name[0]?.toUpperCase()}</span><span><strong>{candidate.name}</strong><small>Author</small></span></button>)}</div>}</div><footer><small>{user?'Type @ to mention someone':'Sign in to join the conversation'}</small><div>{parent&&<button type="button" onClick={onCancel}>Cancel</button>}<button className="button" disabled={busy}><Send aria-hidden="true"/>{busy?'Publishing…':parent?'Reply':'Publish response'}</button></div></footer></form>
}

export function ThreadedComments({post,initialComments}: {post:Post;initialComments:Comment[]}) {
  const {user}=useAuth();const toast=useToast();const navigate=useNavigate();const [comments,setComments]=useState(initialComments);const [postReactions,setPostReactions]=useState(post.reactions??[]);const [replying,setReplying]=useState('');const [sort,setSort]=useState<'newest'|'popular'>('newest');const [authors,setAuthors]=useState<User[]>([])
  useEffect(()=>setComments(initialComments),[initialComments]);useEffect(()=>setPostReactions(post.reactions??[]),[post.reactions])
  useEffect(()=>{const values=[post.author,...comments.map(item=>item.user)].filter(Boolean) as User[];setAuthors([...new Map(values.map(value=>[value.id,value])).values()])},[post.author,comments])
  const children=useMemo(()=>{const map=new Map<string,Comment[]>();for(const comment of comments){if(comment.parent_id){const values=map.get(comment.parent_id)??[];values.push(comment);map.set(comment.parent_id,values)}}return map},[comments])
  const roots=useMemo(()=>{const ids=new Set(comments.map(comment=>comment.id));return comments.filter(comment=>!comment.parent_id||!ids.has(comment.parent_id)).sort((a,b)=>{if(Boolean(a.is_pinned)!==Boolean(b.is_pinned))return a.is_pinned?-1:1;if(sort==='popular')return reactionTotal(b.reactions)-reactionTotal(a.reactions);return new Date(b.created_at).getTime()-new Date(a.created_at).getTime()})},[comments,sort])
  function requireUser(){if(user)return true;toast('Sign in to react or reply.','info');navigate('/login');return false}
  async function reactPost(type:ReactionType){if(!requireUser()||!user)return;const before=postReactions;setPostReactions(optimisticReaction(before,user.id,type));try{setPostReactions(await api.reactToPost(post.slug,type))}catch{setPostReactions(before);toast('Unable to update reaction.','error')}}
  async function reactComment(comment:Comment,type:ReactionType){if(!requireUser()||!user)return;const before=comment.reactions??[];setComments(values=>values.map(item=>item.id===comment.id?{...item,reactions:optimisticReaction(before,user.id,type)}:item));try{const reactions=await api.reactToComment(comment.id,type);setComments(values=>values.map(item=>item.id===comment.id?{...item,reactions}:item))}catch{setComments(values=>values.map(item=>item.id===comment.id?{...item,reactions:before}:item));toast('Unable to update reaction.','error')}}
  async function pin(comment:Comment){const before=comments;const next=!comment.is_pinned;setComments(values=>values.map(item=>({...item,is_pinned:item.id===comment.id?next:false})));try{await api.pinComment(comment.id,next);toast(next?'Comment pinned.':'Comment unpinned.','info')}catch{setComments(before);toast('Unable to pin comment.','error')}}
  function renderComment(comment:Comment,depth=0):React.ReactNode {const replies=(children.get(comment.id)??[]).sort((a,b)=>new Date(a.created_at).getTime()-new Date(b.created_at).getTime());const isAuthor=comment.user_id===post.author_id||comment.user?.id===post.author_id;return <div className={`thread-node depth-${Math.min(depth,2)}`} key={comment.id}><article className={`thread-comment${comment.is_pinned?' pinned':''}`}><span className="avatar">{comment.user?.avatar?<img src={comment.user.avatar} alt=""/>:comment.user?.name?.[0]?.toUpperCase()??'R'}</span><div><header><strong>{comment.user?.name??'Reader'}</strong>{isAuthor&&<span className="author-badge">Author</span>}{comment.is_pinned&&<span className="pinned-badge"><Pin aria-hidden="true"/>Pinned</span>}<time>{new Intl.DateTimeFormat('en',{month:'short',day:'numeric'}).format(new Date(comment.created_at))}</time></header><p>{comment.content}</p>{comment.status==='pending'&&<small className="pending-label">Awaiting moderation</small>}<footer><ReactionBar reactions={comment.reactions} onReact={type=>void reactComment(comment,type)}/><div><button type="button" onClick={()=>{if(requireUser())setReplying(value=>value===comment.id?'':comment.id)}}><MessageCircle aria-hidden="true"/>Reply</button>{user?.id===post.author_id&&depth===0&&<button type="button" onClick={()=>void pin(comment)}><Pin aria-hidden="true"/>{comment.is_pinned?'Unpin':'Pin'}</button>}</div></footer>{replying===comment.id&&<CommentComposer post={post} parent={comment} candidates={authors} onCancel={()=>setReplying('')} onCreated={created=>{setComments(values=>[...values,created]);setReplying('')}}/>}</div></article>{replies.length>0&&<div className="thread-children">{replies.map(reply=>renderComment(reply,Math.min(depth+1,2)))}</div>}</div>}
  return <><SeriesProgress post={post}/><section className="story-reactions"><div><span className="reaction-kicker">Your reaction</span><strong>What did this story leave with you?</strong></div><ReactionBar reactions={postReactions} onReact={type=>void reactPost(type)}/></section><section className="comments threaded-comments"><header className="conversation-head"><div><span className="conversation-kicker">Join the discussion</span><h2>Conversation <sup>{comments.length}</sup></h2></div><label><span>Sort by</span><span className="comment-sort"><select value={sort} onChange={event=>setSort(event.target.value as 'newest'|'popular')}><option value="newest">Newest</option><option value="popular">Most popular</option></select><ChevronDown aria-hidden="true"/></span></label></header><CommentComposer post={post} candidates={authors} onCreated={created=>setComments(values=>[...values,created])}/>{roots.length?<div className="thread-list">{roots.map(comment=>renderComment(comment))}</div>:<div className="thread-empty"><MessageCircle aria-hidden="true"/><strong>Start the conversation</strong><span>Be the first to share a thoughtful response.</span></div>}</section></>
}
