import { createContext,useContext,useEffect,useState,type ReactNode } from 'react'
type InstallPromptEvent=Event&{prompt():Promise<void>;userChoice:Promise<{outcome:'accepted'|'dismissed'}>}
type PWAValue={online:boolean;canInstall:boolean;install():Promise<void>}
const PWAContext=createContext<PWAValue>({online:navigator.onLine,canInstall:false,install:async()=>{}})
export function PWAProvider({children}:{children:ReactNode}){const[online,setOnline]=useState(navigator.onLine);const[prompt,setPrompt]=useState<InstallPromptEvent|null>(null);const[update,setUpdate]=useState<ServiceWorker|null>(null)
 useEffect(()=>{const on=()=>setOnline(true),off=()=>setOnline(false),install=(event:Event)=>{event.preventDefault();setPrompt(event as InstallPromptEvent)};window.addEventListener('online',on);window.addEventListener('offline',off);window.addEventListener('beforeinstallprompt',install);if('serviceWorker'in navigator){if(import.meta.env.PROD)navigator.serviceWorker.register('/sw.js').then(registration=>{if(registration.waiting)setUpdate(registration.waiting);registration.addEventListener('updatefound',()=>{const next=registration.installing;if(next)next.addEventListener('statechange',()=>{if(next.state==='installed'&&navigator.serviceWorker.controller)setUpdate(next)})})}).catch(()=>null);else navigator.serviceWorker.getRegistrations().then(values=>values.filter(value=>value.active?.scriptURL.endsWith('/sw.js')).forEach(value=>void value.unregister()))}return()=>{window.removeEventListener('online',on);window.removeEventListener('offline',off);window.removeEventListener('beforeinstallprompt',install)}},[])
 useEffect(()=>{const changed=()=>location.reload();navigator.serviceWorker?.addEventListener('controllerchange',changed);return()=>navigator.serviceWorker?.removeEventListener('controllerchange',changed)},[])
 async function install(){if(!prompt)return;await prompt.prompt();await prompt.userChoice;setPrompt(null)}function apply(){update?.postMessage({type:'SKIP_WAITING'})}
 return <PWAContext.Provider value={{online,canInstall:Boolean(prompt),install}}>{children}{!online&&<div className="offline-banner" role="status"><span>○</span> Bạn đang offline — nội dung đã lưu vẫn có thể đọc.</div>}{update&&<div className="pwa-update" role="status"><span>Có bản cập nhật mới.</span><button type="button" onClick={apply}>Tải lại trang</button><button type="button" aria-label="Dismiss" onClick={()=>setUpdate(null)}>×</button></div>}</PWAContext.Provider>}
export function usePWA(){return useContext(PWAContext)}
