import { useEffect,useMemo,useState } from 'react'
import { Link,useNavigate,useParams } from 'react-router-dom'
import { BlogCard } from '../components/BlogCard'
import { EmptyState,ErrorState,Layout,Loading } from '../components/ui'
import { useAuth } from '../hooks/useAuth'
import { api } from '../services/api'
import type { AuthorPageData,Category,FollowState } from '../types'
import { ViewToggle } from '../components/ViewToggle'

function safeLink(value?:string){if(!value)return '';try{const url=new URL(value);return ['http:','https:'].includes(url.protocol)?url.href:''}catch{return ''}}

export function AuthorPage(){
 const{username=''}=useParams();const navigate=useNavigate();const{user}=useAuth();const[data,setData]=useState<AuthorPageData|null>(null);const[categories,setCategories]=useState<Category[]>([]);const[category,setCategory]=useState('');const[follow,setFollow]=useState<FollowState>({following:false,follower_count:0});const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[error,setError]=useState('')
 useEffect(()=>{let active=true;setLoading(true);setError('');setData(null);Promise.all([api.author(username),api.categories()]).then(([value,taxonomy])=>{if(!active)return;setData({...value,posts:Array.isArray(value.posts)?value.posts:[],series:Array.isArray(value.series)?value.series:[]});setCategories(Array.isArray(taxonomy)?taxonomy:[]);setFollow(current=>({...current,follower_count:value.follower_count??0}));return api.authorFollow(username).then(result=>{if(active)setFollow(result)}).catch(()=>null)}).catch(err=>{if(active)setError(err instanceof Error?err.message:'Author not found')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[username])
 useEffect(()=>{if(!data)return;const description=data.author.bio||`Read the latest stories and series by ${data.author.name} on Lumina.`;document.title=`${data.author.name} — Author at Lumina`;const meta=(selector:string,property:string,value:string)=>{let node=document.head.querySelector<HTMLMetaElement>(selector);if(!node){node=document.createElement('meta');const[key,name]=property.split('=');node.setAttribute(key,name);document.head.appendChild(node)}node.content=value};meta('meta[name="description"]','name=description',description);meta('meta[property="og:title"]','property=og:title',document.title);meta('meta[property="og:description"]','property=og:description',description);meta('meta[property="og:type"]','property=og:type','profile');if(data.author.avatar)meta('meta[property="og:image"]','property=og:image',new URL(data.author.avatar,location.origin).href)},[data])
 const usedCategories=useMemo(()=>categories.filter(item=>data?.posts.some(post=>post.category_ids?.includes(item.id))),[categories,data]);const posts=category?data?.posts.filter(post=>post.category_ids?.includes(category))??[]:data?.posts??[];const pinned=posts.filter(post=>post.is_pinned_on_profile);const regular=posts.filter(post=>!post.is_pinned_on_profile);const own=user?.id===data?.author.id
 async function toggleFollow(){if(!data)return;if(!user){navigate('/login');return}setBusy(true);const before=follow;setFollow(value=>({following:!value.following,follower_count:Math.max(0,value.follower_count+(value.following?-1:1))}));try{setFollow(await(before.following?api.unfollowAuthor(data.author.id):api.followAuthor(data.author.id)))}catch{setFollow(before)}finally{setBusy(false)}}
 if(loading)return <Layout dark><Loading/></Layout>;if(error||!data)return <Layout dark><ErrorState message={error||'Author not found'}/></Layout>;const socials=data.author.social_links??{}
 return <Layout dark><section className="public-author"><header className="author-hero"><div className="author-avatar">{data.author.avatar?<img src={data.author.avatar} alt={`${data.author.name}'s avatar`}/>:data.author.name[0]?.toUpperCase()}</div><div className="author-intro"><span className="eyebrow">LUMINA AUTHOR</span><h1>{data.author.name}</h1><p>{data.author.bio||'A thoughtful voice in the Lumina community.'}</p><div className="author-socials">{safeLink(socials.website)&&<a href={safeLink(socials.website)} target="_blank" rel="noreferrer">Website ↗</a>}{safeLink(socials.x)&&<a href={safeLink(socials.x)} target="_blank" rel="noreferrer">X ↗</a>}{safeLink(socials.linkedin)&&<a href={safeLink(socials.linkedin)} target="_blank" rel="noreferrer">LinkedIn ↗</a>}{Array.isArray(socials.links)&&socials.links.map((link,index)=>safeLink(link.url)?<a href={safeLink(link.url)} target="_blank" rel="noreferrer" key={`${link.name}-${index}`}>{link.name} ↗</a>:null)}</div></div><aside><div><strong>{data.post_count}</strong><span>Stories</span></div><div><strong>{follow.follower_count}</strong><span>Followers</span></div>{own?<Link to="/profile/settings">Edit profile</Link>:<button type="button" className={follow.following?'following':''} disabled={busy} aria-pressed={follow.following} onClick={()=>void toggleFollow()}>{busy?'Saving…':follow.following?'Following':'Follow'}</button>}</aside></header>
 {pinned.length>0&&<section className="author-pinned"><header><span className="eyebrow">PINNED BY {data.author.name.toUpperCase()}</span><h2>Start here</h2></header><div>{pinned.map(post=><BlogCard post={post} key={post.id}/>)}</div></section>}
 {data.series.length>0&&<section className="author-series"><header><span className="eyebrow">CURATED JOURNEYS</span><h2>Series by {data.author.name}</h2></header><div>{data.series.map(value=><Link to={`/series/${value.slug}`} key={value.id}><span>{value.cover_image?<img src={value.cover_image.url} alt="" loading="lazy"/>:'L'}</span><div><small>{value.posts?.length??0} parts</small><h3>{value.title}</h3><p>{value.description}</p></div></Link>)}</div></section>}
 <section className="author-stories"><header><div><span className="eyebrow">LATEST WRITING</span><h2>Stories</h2></div><ViewToggle targetId="author-stories-view" storageKey="author-stories"/>{usedCategories.length>1&&<label><span>Topic</span><select className="app-native-select" value={category} onChange={event=>setCategory(event.target.value)}><option value="">All topics</option>{usedCategories.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label>}</header>{regular.length?<div className="post-grid" id="author-stories-view">{regular.map(post=><BlogCard post={post} key={post.id}/>)}</div>:<EmptyState title={category?'No stories in this topic yet':`${data.author.name} is preparing their first story`} text={category?'Choose another topic to keep exploring.':'Come back soon for something thoughtful.'}/>}</section></section></Layout>
}
