import { useEffect,useState,type FormEvent } from 'react'
import { Navigate } from 'react-router-dom'
import { CalendarDays,Check,ChevronDown,ChevronUp,Pencil,Plus,Share2,Target as TargetIcon,Trash2,X } from 'lucide-react'
import { confirmAction } from '../components/ConfirmModal'
import { EmptyState,Layout,Loading } from '../components/ui'
import { useAuth } from '../hooks/useAuth'
import { useToast } from '../hooks/useToast'
import { api } from '../services/api'
import type { Target,Todo } from '../types'

function progress(target:Target){return target.todos.length?Math.round(target.todos.filter(todo=>todo.completed).length/target.todos.length*100):0}
function ProgressRing({value}:{value:number}){const level=value===100?'complete':value>=70?'high':value>=35?'medium':'low';return <div className={`target-progress ${level}`} aria-label={`${value}% complete`} style={{'--progress':value} as React.CSSProperties}><svg viewBox="0 0 44 44" aria-hidden="true"><circle cx="22" cy="22" r="18"/><circle className="value" cx="22" cy="22" r="18"/></svg><strong>{value}%</strong></div>}
function localDate(value:string){return value.slice(0,10)}

export function TodoPage(){
 const{user,loading:authLoading}=useAuth();const toast=useToast()
 const[targets,setTargets]=useState<Target[]>([]),[legacy,setLegacy]=useState<Todo[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[error,setError]=useState('')
 const[dateType,setDateType]=useState<'created'|'due'>('due'),[dateFilter,setDateFilter]=useState(''),[open,setOpen]=useState<Record<string,boolean>>({}),[drafts,setDrafts]=useState<Record<string,string>>({}),[editingTodo,setEditingTodo]=useState('')
 const[editing,setEditing]=useState<Target|null|undefined>(undefined),[title,setTitle]=useState(''),[description,setDescription]=useState(''),[dueDate,setDueDate]=useState('')
 const[sharing,setSharing]=useState<Target|null>(null),[shareEmail,setShareEmail]=useState('')

 useEffect(()=>{if(!user)return;setLoading(true);const params=new URLSearchParams();if(dateFilter){params.set('date_type',dateType);params.set('date',dateFilter)}Promise.all([api.targets(params.size?`?${params}`:''),api.todos('?unassigned=true&limit=50')]).then(([values,old])=>{setTargets(values??[]);setLegacy(old.items??[])}).catch(err=>{if(err instanceof Error&&err.message.toLowerCase()==='not found'){setTargets([]);setLegacy([])}else setError(err instanceof Error?err.message:'Unable to load targets')}).finally(()=>setLoading(false))},[user,dateType,dateFilter])
 if(authLoading)return <Layout><Loading/></Layout>;if(!user)return <Navigate to="/login" replace/>

 function showTargetModal(target:Target|null){setEditing(target);setTitle(target?.title??'');setDescription(target?.description??'');setDueDate(target?localDate(target.due_date):'')}
 async function saveTarget(event:FormEvent){event.preventDefault();if(!title.trim()||!dueDate)return;setBusy('target-save');try{if(editing){await api.updateTarget({id:editing.id,title:title.trim(),description:description.trim(),due_date:dueDate});setTargets(current=>current.map(item=>item.id===editing.id?{...item,title:title.trim(),description:description.trim(),due_date:dueDate}:item))}else{const value=await api.createTarget(title.trim(),description.trim(),dueDate);setTargets(current=>[...current,value].sort((a,b)=>a.due_date.localeCompare(b.due_date)));setOpen(current=>({...current,[value.id]:true}))}setEditing(undefined);toast(editing?'Target updated.':'Target created.')}catch(err){setError(err instanceof Error?err.message:'Unable to save target')}finally{setBusy('')}}
 async function share(event:FormEvent){event.preventDefault();if(!sharing||!shareEmail.trim())return;setBusy('share');try{await api.shareTarget(sharing.id,shareEmail.trim());setSharing(null);setShareEmail('');toast('Target shared. The recipient can only check todos.')}catch(err){setError(err instanceof Error?err.message:'Unable to share target')}finally{setBusy('')}}
 async function addTodo(targetId:string,event:FormEvent){event.preventDefault();const value=drafts[targetId]?.trim();if(!value)return;setBusy(`new-${targetId}`);try{const todo=await api.createTargetTodo(targetId,value,'');setTargets(current=>current.map(target=>target.id===targetId?{...target,todos:[...target.todos,todo]}:target));setDrafts(current=>({...current,[targetId]:''}))}catch(err){setError(err instanceof Error?err.message:'Unable to add todo')}finally{setBusy('')}}
 async function toggle(todo:Todo){setBusy(todo.id);try{const value=await api.checkTodo(todo.id,!todo.completed);setTargets(current=>current.map(target=>({...target,todos:target.todos.map(item=>item.id===value.id?value:item)})));setLegacy(current=>current.map(item=>item.id===value.id?value:item))}catch(err){setError(err instanceof Error?err.message:'Unable to update todo')}finally{setBusy('')}}
 async function rename(todo:Todo,titleValue:string){const next=titleValue.trim();if(!next){setEditingTodo('');return}if(next===todo.title){setEditingTodo('');return}setBusy(todo.id);try{const value=await api.updateTodo({...todo,title:next});setTargets(current=>current.map(target=>({...target,todos:target.todos.map(item=>item.id===value.id?value:item)})));setEditingTodo('')}catch(err){setError(err instanceof Error?err.message:'Unable to rename todo')}finally{setBusy('')}}
 async function removeTodo(todo:Todo){if(!await confirmAction({title:'Delete todo?',message:`“${todo.title}” will be permanently deleted.`,confirmLabel:'Delete',danger:true}))return;setBusy(todo.id);try{await api.deleteTodo(todo.id);setTargets(current=>current.map(target=>({...target,todos:target.todos.filter(item=>item.id!==todo.id)})));setLegacy(current=>current.filter(item=>item.id!==todo.id))}finally{setBusy('')}}
 async function removeTarget(target:Target){if(!await confirmAction({title:'Delete target?',message:`“${target.title}” and all todos will be deleted.`,confirmLabel:'Delete target',danger:true}))return;setBusy(target.id);try{await api.deleteTarget(target.id);setTargets(current=>current.filter(item=>item.id!==target.id))}finally{setBusy('')}}
 function todoRow(todo:Todo,canEdit:boolean){const isEditing=canEdit&&editingTodo===todo.id;return <article className={todo.completed?'completed':''} key={todo.id}><button className="todo-check" type="button" disabled={busy===todo.id} aria-pressed={todo.completed} aria-label={todo.title} onClick={()=>void toggle(todo)}>{todo.completed&&<Check/>}</button><div>{isEditing?<input className="todo-inline-title" defaultValue={todo.title} disabled={busy===todo.id} onBlur={event=>void rename(todo,event.target.value)} onKeyDown={event=>{if(event.key==='Enter')event.currentTarget.blur();if(event.key==='Escape'){event.currentTarget.value=todo.title;event.currentTarget.blur()}}} aria-label="Todo title" autoFocus/>:<h3>{todo.title}</h3>}{todo.notes&&<p>{todo.notes}</p>}</div>{canEdit&&<div className="todo-actions"><button className="todo-edit" type="button" disabled={busy===todo.id} onClick={()=>setEditingTodo(todo.id)} aria-label={`Edit ${todo.title}`}><Pencil/></button><button className="todo-delete" type="button" disabled={busy===todo.id} onClick={()=>void removeTodo(todo)} aria-label={`Delete ${todo.title}`}><Trash2/></button></div>}</article>}

 return <Layout><section className="todo-page target-page container"><header><div><span className="eyebrow">PERSONAL WORKSPACE</span><h1>Targets &amp; todos</h1><p>Turn a meaningful target into small, measurable steps.</p></div><button className="button target-new-button" onClick={()=>showTargetModal(null)}><Plus/>New target</button></header>
  <section className="target-filter"><div><strong>Find targets by date</strong><span>Choose which date you want to match.</span></div><div className="target-filter-types"><button className={dateType==='created'?'active':''} onClick={()=>setDateType('created')}>Created date</button><button className={dateType==='due'?'active':''} onClick={()=>setDateType('due')}>Completion date</button></div><label><CalendarDays/><input type="date" value={dateFilter} onChange={event=>setDateFilter(event.target.value)}/></label>{dateFilter&&<button className="target-filter-clear" onClick={()=>setDateFilter('')}>Clear</button>}</section>
  {error&&<div className="admin-alert">{error}<button onClick={()=>setError('')}>×</button></div>}{loading?<Loading/>:targets.length?<div className="target-list">{targets.map(target=>{const expanded=open[target.id]??true;return <section className="target-card" key={target.id}><header><ProgressRing value={progress(target)}/><div><span><CalendarDays/>Due {new Intl.DateTimeFormat('en',{dateStyle:'medium'}).format(new Date(target.due_date))}{target.is_shared&&<b className="shared-badge">Shared with you</b>}</span><h2>{target.title}</h2>{target.description&&<p>{target.description}</p>}<small>{target.todos.filter(todo=>todo.completed).length} of {target.todos.length} todos completed</small></div><div>{target.can_edit&&<><button className="target-expand" onClick={()=>showTargetModal(target)} aria-label="Edit target"><Pencil/></button><button className="target-expand" onClick={()=>{setSharing(target);setShareEmail('')}} aria-label="Share target"><Share2/></button></>}<button className="target-expand" onClick={()=>setOpen(current=>({...current,[target.id]:!expanded}))}>{expanded?<ChevronUp/>:<ChevronDown/>}</button>{target.can_edit&&<button className="todo-delete" onClick={()=>void removeTarget(target)}><Trash2/></button>}</div></header>{expanded&&<div className="target-body"><div className="target-todos">{target.todos.length?target.todos.map(todo=>todoRow(todo,target.can_edit)):<p className="target-empty">No steps yet.</p>}</div>{target.can_edit&&<form className="target-add-todo" onSubmit={event=>void addTodo(target.id,event)}><input value={drafts[target.id]??''} onChange={event=>setDrafts(current=>({...current,[target.id]:event.target.value}))} placeholder="Add the next step…" required/><button><Plus/>Add todo</button></form>}</div>}</section>})}</div>:<EmptyState title={dateFilter?'No targets on this date':'No targets yet'} text={dateFilter?'Try another date or clear the filter.':'Create your first target and break it into achievable todos.'}/>}{legacy.length>0&&<section className="legacy-todos"><h2>Previous standalone todos</h2><div className="target-todos">{legacy.map(todo=>todoRow(todo,true))}</div></section>}
  {editing!==undefined&&<div className="target-modal" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)setEditing(undefined)}}><form role="dialog" aria-modal="true" onSubmit={saveTarget}><header><TargetIcon/><div><h2>{editing?'Edit target':'Create a target'}</h2><p>{editing?'Update the target and completion date.':'Set the finish line, then add the steps.'}</p></div><button type="button" onClick={()=>setEditing(undefined)}><X/></button></header><label><span>Target</span><input value={title} onChange={event=>setTitle(event.target.value)} maxLength={160} required autoFocus/></label><label><span>Completion date</span><input type="date" value={dueDate} onChange={event=>setDueDate(event.target.value)} required/></label><label><span>Description</span><textarea value={description} onChange={event=>setDescription(event.target.value)} maxLength={1000}/></label><footer><button type="button" onClick={()=>setEditing(undefined)}>Cancel</button><button className="button" disabled={busy==='target-save'}>{busy==='target-save'?'Saving…':editing?'Save changes':'Create target'}</button></footer></form></div>}
  {sharing&&<div className="target-modal" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)setSharing(null)}}><form role="dialog" aria-modal="true" onSubmit={share}><header><Share2/><div><h2>Share target</h2><p>The recipient can check todos, but cannot edit anything.</p></div><button type="button" onClick={()=>setSharing(null)}><X/></button></header><label><span>Account email</span><input type="email" value={shareEmail} onChange={event=>setShareEmail(event.target.value)} placeholder="reader@example.com" required autoFocus/></label><small className="share-privacy">Recipients cannot see who else this target is shared with.</small><footer><button type="button" onClick={()=>setSharing(null)}>Cancel</button><button className="button" disabled={busy==='share'}>{busy==='share'?'Sharing…':'Share access'}</button></footer></form></div>}
 </section></Layout>
}
