import { useEffect,useState,type FormEvent } from 'react'
import { Navigate } from 'react-router-dom'
import { Check,Plus,Search,Trash2 } from 'lucide-react'
import { confirmAction } from '../components/ConfirmModal'
import { EmptyState,Layout,Loading,Pagination } from '../components/ui'
import { useAuth } from '../hooks/useAuth'
import { useToast } from '../hooks/useToast'
import { api } from '../services/api'
import type { Todo } from '../types'

export function TodoPage(){
 const{user,loading:authLoading}=useAuth();const toast=useToast();const[items,setItems]=useState<Todo[]>([]);const[loading,setLoading]=useState(true);const[query,setQuery]=useState('');const[search,setSearch]=useState('');const[status,setStatus]=useState('all');const[page,setPage]=useState(1);const[total,setTotal]=useState(0);const[title,setTitle]=useState('');const[notes,setNotes]=useState('');const[busy,setBusy]=useState('');const[error,setError]=useState('')
 useEffect(()=>{if(!user)return;const params=new URLSearchParams({page:String(page)});if(search)params.set('q',search);if(status!=='all')params.set('status',status);setLoading(true);setError('');api.todos(`?${params}`).then(value=>{setItems(value.items??[]);setTotal(value.total)}).catch(err=>{const message=err instanceof Error?err.message:'Unable to load todos';if(message.toLowerCase()==='not found'){setItems([]);setTotal(0)}else setError(message)}).finally(()=>setLoading(false))},[user,page,search,status])
 if(authLoading)return <Layout><Loading/></Layout>;if(!user)return <Navigate to="/login" replace/>
 async function create(event:FormEvent){event.preventDefault();if(!title.trim())return;setBusy('new');try{const value=await api.createTodo(title.trim(),notes.trim());setItems(current=>[value,...current]);setTotal(value=>value+1);setTitle('');setNotes('');toast('Task added.')}catch(err){setError(err instanceof Error?err.message:'Unable to add task')}finally{setBusy('')}}
 async function toggle(todo:Todo){const next=!todo.completed;if(!await confirmAction({title:next?'Complete this task?':'Reopen this task?',message:`“${todo.title}” will be marked ${next?'completed':'active'}.`,confirmLabel:next?'Complete':'Reopen'}))return;setBusy(todo.id);try{const value=await api.updateTodo({...todo,completed:next});setItems(current=>current.map(item=>item.id===value.id?value:item))}catch(err){setError(err instanceof Error?err.message:'Unable to update task')}finally{setBusy('')}}
 async function remove(todo:Todo){if(!await confirmAction({title:'Delete task?',message:`“${todo.title}” will be permanently deleted.`,confirmLabel:'Delete task',danger:true}))return;setBusy(todo.id);try{await api.deleteTodo(todo.id);setItems(current=>current.filter(item=>item.id!==todo.id));setTotal(value=>Math.max(0,value-1));toast('Task deleted.')}catch(err){setError(err instanceof Error?err.message:'Unable to delete task')}finally{setBusy('')}}
 return <Layout><section className="todo-page container"><header><div><span className="eyebrow">PERSONAL WORKSPACE</span><h1>Todo list</h1><p>Keep track of tasks, lessons, and ideas tied only to your account.</p></div><strong>{items.filter(item=>item.completed).length}/{total} done</strong></header><form className="todo-create" onSubmit={create}><div><label><span>Task</span><input value={title} onChange={event=>setTitle(event.target.value)} maxLength={160} placeholder="What needs to be done?" required/></label><label><span>Notes</span><input value={notes} onChange={event=>setNotes(event.target.value)} maxLength={1000} placeholder="Optional context or details"/></label></div><button className="button" disabled={busy==='new'}><Plus aria-hidden="true"/>{busy==='new'?'Adding…':'Add task'}</button></form><div className="todo-toolbar"><form onSubmit={event=>{event.preventDefault();setPage(1);setSearch(query.trim())}}><Search aria-hidden="true"/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search tasks…"/><button>Search</button></form><div>{['all','active','completed'].map(value=><button type="button" className={status===value?'active':''} onClick={()=>{setStatus(value);setPage(1)}} key={value}>{value}</button>)}</div></div>{error&&<div className="admin-alert">{error}<button onClick={()=>setError('')}>×</button></div>}{loading?<Loading/>:items.length?<div className="todo-list">{items.map(todo=><article className={todo.completed?'completed':''} key={todo.id}><button className="todo-check" type="button" disabled={busy===todo.id} aria-label={todo.completed?'Reopen task':'Complete task'} onClick={()=>void toggle(todo)}>{todo.completed&&<Check aria-hidden="true"/>}</button><div><h2>{todo.title}</h2>{todo.notes&&<p>{todo.notes}</p>}<small>Updated {new Intl.DateTimeFormat('en',{dateStyle:'medium'}).format(new Date(todo.updated_at))}</small></div><button className="todo-delete" type="button" disabled={busy===todo.id} aria-label={`Delete ${todo.title}`} onClick={()=>void remove(todo)}><Trash2 aria-hidden="true"/></button></article>)}</div>:<EmptyState title="No tasks found" text="Add a task or change the current search and status filter."/>}<Pagination page={page} total={total} limit={10} onPage={setPage}/></section></Layout>
}
