import React from 'react'
import ReactDOM from 'react-dom/client'
import { BrowserRouter } from 'react-router-dom'
import App from './App'
import { AuthProvider } from './hooks/useAuth'
import { ToastProvider } from './hooks/useToast'
import { BookmarkProvider } from './hooks/useBookmarks'
import { PWAProvider } from './hooks/usePWA'
import { ConfirmModal } from './components/ConfirmModal'
import { I18nProvider } from './i18n'
import { previewFont, savedFont } from './font'
import './styles.css'
import './inline-taxonomy.css'
import './settings.css'
import './profile-actions.css'
import './avatar.css'
import './markdown-view.css'
import './theme.css'
import './density.css'
import './sprint-upgrades.css'
import './global-polish.css'
import './command-palette.css'
import './mobile-nav.css'
import './editorial-home.css'
import './threaded-comments.css'
import './series.css'
import './selection-quote.css'
import './author-page.css'
import './pwa.css'
import './auth-settings-polish.css'
import './icon-system.css'
import './view-confirm.css'
import './view-confirm-extra.css'
import './productivity.css'
import './discussion-editor.css'
import './productivity-themes.css'
import './form-controls.css'
import './i18n.css'
import './personal.css'
previewFont(savedFont())
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><I18nProvider><BrowserRouter><ToastProvider><PWAProvider><AuthProvider><BookmarkProvider><App/><ConfirmModal/></BookmarkProvider></AuthProvider></PWAProvider></ToastProvider></BrowserRouter></I18nProvider></React.StrictMode>)
